export { TabApertureComponent as TabAperture } from './tab-aperture/tab-aperture.component'
export { TabInfoBaseComponent as TabInfoBase } from './tab-info-base/tab-info-base.component'
export { TabEventiComponent as TabEventi } from './tab-eventi/tab-eventi.component'
export { TabServiziComponent as TabServizi } from './tab-servizi/tab-servizi.component'
export { TabTariffarioComponent as TabTariffario } from './tab-tariffario/tab-tariffario.component'
export { TabRestrizioniComponent as TabRestrizioni } from './tab-restrizioni/tab-restrizioni.component'
