const segnalaME = {
  superAdmin: ['impleme-master'],
  sysAdmin: ['impleme-admsys_segnala'],
  serviceAdmin: ['impleme-adm_segnala'],
  operator: ['impleme-operatore_segnala'],
}

const prenotaUfficio = {
  superAdmin: ['impleme-master'],
  sysAdmin: ['impleme-admsys_prenuff'],
  serviceAdmin: ['impleme-adm_prenuff'],
  operator: ['impleme-operatore_prenuff'],
}

const APP_ROUTING_ACL = {
  prenotame: [
    'impleme-master',
    'impleme-admsys_spazio',
    'impleme-adm_spazio',
    'impleme-operatore_spazio',
  ],
  'struttura/create': [
    // 'impleme-master',
    // 'impleme-admsys_spazio',
    'impleme-adm_spazio',
  ],
  'struttura/update': [
    // 'impleme-master',
    // 'impleme-admsys_spazio',
    'impleme-adm_spazio',
  ],
  'struttura/preview': [
    'impleme-master',
    'impleme-admsys_spazio',
    'impleme-adm_spazio',
    'impleme-operatore_spazio',
  ],
  'struttura/categoria/index': [
    'impleme-master',
    'impleme-admsys_spazio',
    'impleme-adm_spazio',
    'impleme-operatore_spazio',
  ],
  'struttura/categoria/create': [
    // 'impleme-master',
    // 'impleme-admsys_spazio',
    'impleme-adm_spazio',
    // 'impleme-operatore_spazio',
  ],
  'struttura/tipologia/index': [
    'impleme-master',
    'impleme-admsys_spazio',
    'impleme-adm_spazio',
    'impleme-operatore_spazio',
  ],
  'struttura/tipologia/create': [
    // 'impleme-master',
    // 'impleme-admsys_spazio',
    'impleme-adm_spazio',
    // 'impleme-operatore_spazio',
  ],
  'prenotazione-sala/revoca': ['impleme-adm_spazio', 'impleme-operatore_spazio'],
  'prenotazione-sala/index': ['impleme-adm_spazio', 'impleme-operatore_spazio'],
  'tributi/index': [
    'impleme-master',
    'impleme-admsys_spazio',
    'impleme-adm_spazio',
    'impleme-admsys_pass',
    'impleme-adm_pass',
    'impleme-admsys_aff',
    'impleme-adm_aff',
    'impleme-admsys_pubbaff',
    'impleme-adm_pubbaff',
    'impleme-admsys_cimit',
    'impleme-adm_cimit',
  ],
  'tributi/create': [
    'impleme-master',
    'impleme-admsys_spazio',
    'impleme-admsys_pass',
    'impleme-admsys_aff',
    'impleme-admsys_pubbaff',
    'impleme-admsys_cimit',
  ],
  'tariffe/create': [
    // 'impleme-admsys_spazio',
    'impleme-adm_spazio',
    // 'impleme-admsys_pass',
    'impleme-adm_pass',
    // 'impleme-admsys_aff',
    'impleme-adm_aff',
    // 'impleme-admsys_pubbaff',
    'impleme-adm_pubbaff',
    // 'impleme-admsys_cimit',
    'impleme-adm_cimit',
  ],
  'tributi/csv': [
    'impleme-master',
    'impleme-adm_spazio',
    'impleme-adm_pass',
    'impleme-adm_aff',
    'impleme-adm_pubbaff',
    'impleme-adm_cimit',
  ],
  'user-tasks/claim': [
    // 'impleme-master',
    // 'impleme-admsys_spazio',
    // 'impleme-adm_spazio',
    'impleme-operatore_spazio',
  ],
  'user-tasks/complete': [
    // 'impleme-master',
    // 'impleme-admsys_spazio',
    // 'impleme-adm_spazio',
    'impleme-operatore_spazio',
  ],
  'report-pagamenti/download-csv': [
    'impleme-master',
    'impleme-adm_spazio',
    'impleme-adm_pass',
    'impleme-adm_aff',
    'impleme-adm_pubbaff',
    'impleme-adm_cimit',
  ],
  segnalame: [
    ...segnalaME.superAdmin,
    ...segnalaME.sysAdmin,
    ...segnalaME.serviceAdmin,
    ...segnalaME.operator,
  ],
  'segnalame/users': [...segnalaME.superAdmin, ...segnalaME.sysAdmin, ...segnalaME.serviceAdmin],
  'segnalame/settings': [...segnalaME.superAdmin, ...segnalaME.sysAdmin, ...segnalaME.serviceAdmin],
  'segnalame/settings/institutes': [...segnalaME.superAdmin, ...segnalaME.sysAdmin],
  prenotaUfficio: [
    ...prenotaUfficio.superAdmin,
    ...prenotaUfficio.sysAdmin,
    ...prenotaUfficio.serviceAdmin,
    ...prenotaUfficio.operator,
  ],
  'prenotaUfficio/settings': [...prenotaUfficio.superAdmin, ...prenotaUfficio.sysAdmin],
  'passicarrabili/index': [
    'impleme-master',
    'impleme-adm_pass',
    'impleme-admsys_pass',
    'impleme-operatore_pass',
  ],
  'passicarrabili/types/create': ['impleme-master', 'impleme-admsys_pass'],
}

export { APP_ROUTING_ACL }
